<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="apples-MacBook-Pro.local" name="com.myProject.Automation.MobileTest.MobileHome" tests="5" failures="0" timestamp="2020-07-04T08:13:57 IST" time="1098.565" errors="1">
  <testcase name="loginAsUser" time="158.943" classname="com.myProject.Automation.MobileTest.MobileHome"/>
  <testcase name="afterSuite" time="0.304" classname="com.myProject.Automation.MobileTest.MobileHome">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.myProject.Automation.Report.endReport(Report.java:50)
at com.myProject.Automation.BaseTest.afterSuite(BaseTest.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:369)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterSuite -->
  <testcase name="placeOrder" time="742.007" classname="com.myProject.Automation.MobileTest.MobileHome"/>
  <testcase name="purchaseMobile" time="186.756" classname="com.myProject.Automation.MobileTest.MobileHome"/>
  <testcase name="selectCategory" time="10.555" classname="com.myProject.Automation.MobileTest.MobileHome"/>
</testsuite> <!-- com.myProject.Automation.MobileTest.MobileHome -->
